GCBias: false
NMaskedIndex: ''
SNPfile: ''
UMIBarcode: false
UMIDedup: true
UMIDedupOpts: --paired
UMIDedupSep: _
VCFfile: ''
aligner: Bowtie2
alignerOpts: null
allele_mode: null
baseDir: /home/ferrari/anaconda3/envs/snakepipes_dev/lib/python3.7/site-packages/snakePipes
bcPattern: NNNNCCCCCCCC
bwBinSize: 25
clusterConfigFile: null
configFile: DNA-mapping_Drosophila_demultiplexed_defaults.yaml
createDAG: false
dedup: false
downsample: null
emailAddress: null
emailSender: null
ext: .fastq.gz
fastqc: false
fragmentLength: 200
genome: dm6
indir: /data/manke/group/ferrari/PhD_project/reference_datasets/autoRELACS_dataset/fastq_files_Drosophila
insertSizeMax: 1000
keepTemp: false
local: false
mapq: 3
mateOrientation: --fr
maxJobs: 10
mode: mapping
onlySSL: false
outdir: /data/manke/group/ferrari/PhD_project/reference_datasets/autoRELACS_dataset/output_snakePipes_Drosophila_demultiplexed
pipeline: dna-mapping
plotFormat: png
properPairs: false
qualimap: false
reads:
- _R1
- _R2
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix ~/anaconda3/envs/ '
strains: ''
tempDir: /data/extended/
trim: true
trimmer: cutadapt
trimmerOptions: null
verbose: false
workingdir: /data/manke/group/ferrari/PhD_project/reference_datasets/autoRELACS_dataset/output_snakePipes_Drosophila_demultiplexed
